name: fmts
channels:
    - defaults
    - conda-forge
dependencies:
- python=3.5
- cython
- pandas
- jupyter
- feather-format
- fastparquet
- python-snappy
- bcolz
- seaborn
- cython
- pip:
  - Brotli
